# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Install and Start Backend
    init: pnpm install
    command: pnpm run server

  - name: Start Frontend
    command: npx wait-on http://localhost:5000 && npm run start

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: BackEnd
    description: Port 5000 for the frontend
    port: 5000
    onOpen: open-preview
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
